/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Author: jimbogies (https://sketchfab.com/jimbogies)
License: CC-BY-4.0 (http://creativecommons.org/licenses/by/4.0/)
Source: https://sketchfab.com/3d-models/american-road-179a1e6a0a154031a60f300fc73d9dd8
Title: American Road
*/
'use client'
import React, { useRef } from 'react'
import { useGLTF } from '@react-three/drei'

const Environment = (props) => {
  const { nodes, materials } = useGLTF('/models/scene.glb')
  return (
    <group {...props} dispose={null} >
      <group rotation={[Math.PI / 2, 0, 0]}>
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Material2.geometry}
          material={materials.RoadLines}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Material2_1.geometry}
          material={materials.Sidewalk01}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Material2_2.geometry}
          material={materials.Grass02}
        />
      </group>
    </group>
  )
}

useGLTF.preload('/models/scene.glb')

export default Environment