/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Author: jimbogies (https://sketchfab.com/jimbogies)
License: CC-BY-4.0 (http://creativecommons.org/licenses/by/4.0/)
Source: https://sketchfab.com/3d-models/american-road-179a1e6a0a154031a60f300fc73d9dd8
Title: American Road
*/
'use client'
import React, { useEffect, useRef } from 'react'
import { useFrame, useLoader } from '@react-three/fiber'
import * as THREE from 'three';


const Environment = ({externalRef, isGameOver, ...props}) => {
  const groundref = useRef();
  
  const rockTexture = useLoader(THREE.TextureLoader, '/textures/rock2.jpg');

  // Ensure the texture repeats and wraps correctly
  rockTexture.wrapS = rockTexture.wrapT = THREE.RepeatWrapping;
  rockTexture.repeat.set(2, 2); // Adjust to fit your needs

  useEffect(() => {
    if (externalRef) {
      externalRef.current = groundref.current;
    }
  }, [externalRef]);

  useFrame(() => { 
    if(!isGameOver)
    {
      groundref.current.rotation.x += 0.006
    }
  });

  return (
    <mesh  ref={groundref} receiveShadow castShadow={false} rotateZ={-Math.PI/2} position={[0, -24, 2]}>
          <dodecahedronGeometry args={[26, 3]} />
          <meshStandardMaterial map={rockTexture} color={'0xfffafa'} flatShading    />
    </mesh>
  )
}


export default Environment